### ISSUE TITLE
  File "reduce_graph.py": TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by irisferrazzo** [interactive-cookbook/tagger-parser#20]
Hi @TheresaSchmidt , I've tried to use reduce_graph.py to generate single action graphs with the recipes that have been tagged with bert and newly parsed. What I'm interested in is to extract the edges before the graph gets converted to the conllu format.
When the script tries to open the recipe file (I've tried with 5 different ones so far and it happened always), it detects some objects of NoneType (I don't understand why, the recipes text look normal to me). If I try to rule the error out, some actions (i.e., lines of file) get lost. Do you have any ideas why that may happen?
Thanks in advance!

Full body of the error message:

File "reduce_graph.py", line 348, in <module>
    outfilename,
  File "reduce_graph.py", line 249, in main
    infile, desired
TypeError: cannot unpack non-iterable NoneType object

**Comment by TheresaSchmidt** [comment]
The path to the data might be wrong (will elaborate later).
