### ISSUE TITLE
Evaluation Code Missing?

### ISSUE THREAD

**Issue by TheresaSchmidt** [interactive-cookbook/tagger-parser#7]
The code for the evaluation used to be in [read_prediction.py](https://github.com/interactive-cookbook/tagger-parser/blob/e036a8c2178cba73cc3dd7fe89a2937c4388c4ed/data-conversions/read_prediction.py) accessed as a fourth mode "eval".
Was there a reason we deleted it? Was there a mistake in it? Or did we just move the code to a separate script (would make sense) and forget to upload it?
If nobody objects I'll just upload such a separate script.

**Comment by irisferrazzo** [comment]
How about this, @siyutao @TheresaSchmidt . Do you still need the issue?
